#!/usr/bin/env node
'use strict';
/**
 * Blorq — First-run setup
 * Creates data/ directory with default users.json, settings.json, and .env
 * Run once: npm run setup
 */
const bcrypt = require('bcryptjs');
const fs     = require('fs');
const path   = require('path');
const crypto = require('crypto');

const DATA_DIR     = path.join(__dirname, 'data');
const USERS_FILE   = path.join(DATA_DIR, 'users.json');
const SETTINGS_FILE= path.join(DATA_DIR, 'settings.json');
const ROLES_FILE   = path.join(DATA_DIR, 'role-config.json');
const API_KEYS_FILE= path.join(DATA_DIR, 'api-keys.json');
const ENV_FILE     = path.join(__dirname, '.env');

async function main() {
  console.log('\n  ╔══════════════════════════════════╗');
  console.log('  ║   Blorq — First-Run Setup        ║');
  console.log('  ╚══════════════════════════════════╝\n');

  // Ensure data directory exists
  if (!fs.existsSync(DATA_DIR)) {
    fs.mkdirSync(DATA_DIR, { recursive: true });
    console.log('✅  Created data/');
  }

  // users.json
  if (fs.existsSync(USERS_FILE)) {
    console.log('⚠️   data/users.json already exists — skipping.');
  } else {
    const [adminHash, viewerHash] = await Promise.all([
      bcrypt.hash('admin123',  12),
      bcrypt.hash('viewer123', 12),
    ]);
    fs.writeFileSync(USERS_FILE, JSON.stringify({
      admin:  { password: adminHash,  role: 'admin',  createdAt: new Date().toISOString() },
      viewer: { password: viewerHash, role: 'viewer', createdAt: new Date().toISOString() },
    }, null, 2));
    console.log('✅  data/users.json created');
    console.log('    admin  / admin123  (role: admin)');
    console.log('    viewer / viewer123 (role: viewer)');
    console.log('    ⚠️   Change these passwords on first login!\n');
  }

  // settings.json
  if (!fs.existsSync(SETTINGS_FILE)) {
    fs.writeFileSync(SETTINGS_FILE, JSON.stringify({
      retentionDays: 7,
      webhookUrl:    '',
      enableStream:  true,
      ipWhitelist:   [],
    }, null, 2));
    console.log('✅  data/settings.json created');
  }

  // role-config.json (empty — built-in roles are in-memory)
  if (!fs.existsSync(ROLES_FILE)) {
    fs.writeFileSync(ROLES_FILE, JSON.stringify({}, null, 2));
    console.log('✅  data/role-config.json created');
  }

  // api-keys.json
  if (!fs.existsSync(API_KEYS_FILE)) {
    fs.writeFileSync(API_KEYS_FILE, JSON.stringify([], null, 2));
    console.log('✅  data/api-keys.json created');
  }

  // .env
  if (fs.existsSync(ENV_FILE)) {
    console.log('⚠️   .env already exists — skipping.');
  } else {
    const jwtSecret = crypto.randomBytes(32).toString('hex');
    const apiKey    = 'blq_' + crypto.randomBytes(32).toString('hex');
    fs.writeFileSync(ENV_FILE, [
      '# Blorq Configuration',
      '# Generated by: npm run setup',
      '',
      'NODE_ENV=development',
      'PORT=9900',
      '',
      '# Security — keep these secret!',
      'JWT_SECRET=' + jwtSecret,
      'API_KEY=' + apiKey + '   # Legacy single key — use API key management UI instead',
      '',
      '# Storage',
      'DATA_DIR=./data',
      'LOG_BASE_DIR=./logs',
      'RETENTION_DAYS=7',
      '',
      '# Features',
      'ENABLE_STREAM=true',
      'JWT_EXPIRES_IN=24h',
      '',
      '# CORS (comma-separated)',
      'CORS_ORIGINS=http://localhost:9900',
      '',
      '# Optional webhook for error alerts',
      'WEBHOOK_URL=',
    ].join('\n') + '\n');
    console.log('✅  .env created with generated secrets');
    console.log('    API_KEY=' + apiKey.slice(0, 20) + '…\n');
  }

  // logs directory
  if (!fs.existsSync(path.join(__dirname, 'logs'))) {
    fs.mkdirSync(path.join(__dirname, 'logs'), { recursive: true });
    console.log('✅  logs/ directory created');
  }

  console.log('\n  🚀  Setup complete! Start Blorq:');
  console.log('      npm start\n');
  console.log('      Open: http://localhost:9900\n');
}

main().catch(err => { console.error('Setup error:', err.message); process.exit(1); });
